### ISSUE TITLE
@registry throws Object of type datetime is not JSON serializable

### ISSUE THREAD

**Issue by CharString** [plone/plone.restapi#1189]
The `@registry` endpoint has trouble serving datetime values.

## How to reproduce

```console
$ docker run -e SITE=Plone -p 127.0.0.1:8080:8080 --detach plone:5-alpine
$ pip install --user affen
$ python
```
```python
>>> from pprint import pprint
>>> from affen import Session
>>> plone = Session('admin', 'admin', 'http://127.0.0.1:8080/Plone')
>>> pprint(plone.get('@system').json())
{'@id': 'http://127.0.0.1:8080/Plone/@system',
 'cmf_version': '2.5.0',
 'debug_mode': 'No',
 'pil_version': '6.2.2 (Pillow)',
 'plone_gs_metadata_version_file_system': '5212',
 'plone_gs_metadata_version_installed': '5212',
 'plone_restapi_version': '7.0.0',
 'plone_version': '5.2.4',
 'python_version': '3.8.11 (default, Jun 29 2021, 20:14:17) \n'
                   '[GCC 10.3.1 20210424]',
 'zope_version': '4.5.5'}
>>> plone.registry['plone.app.theming.interfaces.IThemeSettings.custom_css_timestamp']
Traceback (most recent call last):
    ...
HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8080/Plone/@registry/plone.app.theming.interfaces.IThemeSettings.custom_css_timestamp
>>> pprint(plone.get('@registry/plone.app.theming.interfaces.IThemeSettings.custom_css_timestamp').json())
{'message': 'Object of type datetime is not JSON serializable',
 'traceback': ['File '
               '"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py", '
               'line 162, in transaction_pubevents',
               '    yield',
               '',
               '  File '
               '"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py", '
               'line 371, in publish_module',
               '    response = _publish(request, new_mod_info)',
               '',
               '  File '
               '"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py", '
               'line 266, in publish',
               '    result = mapply(obj,',
               '',
               '  File '
               '"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/mapply.py", '
               'line 85, in mapply',
               '    return debug(object, args, context)',
               '',
               '  File '
               '"/plone/buildout-cache/eggs/cp38/Zope-4.5.5-py3.8.egg/ZPublisher/WSGIPublisher.py", '
               'line 63, in call_object',
               '    return obj(*args)',
               '',
               '  File '
               '"/plone/buildout-cache/eggs/cp38/plone.rest-1.6.2-py3.8.egg/plone/rest/service.py", '
               'line 22, in __call__',
               '    return self.render()',
               '',
               '  File '
               '"/plone/buildout-cache/eggs/cp38/plone.restapi-7.0.0-py3.8.egg/plone/restapi/services/__init__.py", '
               'line 23, in render',
               '    return json.dumps(',
               '',
               '  File "/usr/local/lib/python3.8/json/__init__.py", line 234, '
               'in dumps',
               '    return cls(',
               '',
               '  File "/usr/local/lib/python3.8/json/encoder.py", line 201, '
               'in encode',
               '    chunks = list(chunks)',
               '',
               '  File "/usr/local/lib/python3.8/json/encoder.py", line 438, '
               'in _iterencode',
               '    o = _default(o)',
               '',
               '  File "/usr/local/lib/python3.8/json/encoder.py", line 179, '
               'in default',
               "    raise TypeError(f'Object of type {o.__class__.__name__} '"],
 'type': 'TypeError'}

**Comment by Petchesi-Iulian** [comment]
This issue is happening to me aswell with the latest plone.restapi 8.24.1 when using the GET @registry endpoint
