### ISSUE TITLE
KeyError: 'portal' in tests with Python 3.12.1

### ISSUE THREAD

**Issue by wesleybl** [plone/plone.restapi#1740]
Tests with Python 3.12.1 are failing:

```bash
Traceback (most recent call last):
  File "/home/runner/work/plone.restapi/plone.restapi/bin/test", line 289, in <module>
    sys.exit(zope.testrunner.run((['-s', 'plone.restapi', '--auto-color', '--auto-progress']) + [
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/plone.restapi/plone.restapi/eggs/zope.testrunner-6.1-py3.12.egg/zope/testrunner/__init__.py", line 31, in run
    failed = run_internal(defaults, args, script_parts=script_parts, cwd=cwd,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/plone.restapi/plone.restapi/eggs/zope.testrunner-6.1-py3.12.egg/zope/testrunner/__init__.py", line 55, in run_internal
    runner.run()
  File "/home/runner/work/plone.restapi/plone.restapi/eggs/zope.testrunner-6.1-py3.12.egg/zope/testrunner/runner.py", line 191, in run
    self.run_tests()
  File "/home/runner/work/plone.restapi/plone.restapi/eggs/zope.testrunner-6.1-py3.12.egg/zope/testrunner/runner.py", line 292, in run_tests
    self.ran += run_layer(self.options, layer_name, layer, tests,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/plone.restapi/plone.restapi/eggs/zope.testrunner-6.1-py3.12.egg/zope/testrunner/runner.py", line 473, in run_layer
    return run_tests(options, tests, layer_name, failures, errors, skipped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/plone.restapi/plone.restapi/eggs/zope.testrunner-6.1-py3.12.egg/zope/testrunner/runner.py", line 399, in run_tests
    test(result)
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/unittest/case.py", line 692, in __call__
    return self.run(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/unittest/case.py", line 662, in run
    result.stopTest(self)
  File "/home/runner/work/plone.restapi/plone.restapi/eggs/zope.testrunner-6.1-py3.12.egg/zope/testrunner/runner.py", line 1019, in stopTest
    self.testTearDown()
  File "/home/runner/work/plone.restapi/plone.restapi/eggs/zope.testrunner-6.1-py3.12.egg/zope/testrunner/runner.py", line 891, in testTearDown
    layer.testTearDown()
  File "/home/runner/work/plone.restapi/plone.restapi/eggs/plone.app.testing-7.0.1-py3.12.egg/plone/app/testing/layers.py", line 291, in testTearDown
    self.tearDownEnvironment(self["portal"])
                             ~~~~^^^^^^^^^^
  File "/home/runner/work/plone.restapi/plone.restapi/eggs/plone.testing-8.0.4-py3.12.egg/plone/testing/layer.py", line 30, in __getitem__
    raise KeyError(key)
KeyError: 'portal'
```

See: https://github.com/plone/plone.restapi/actions/runs/7232945652/job/19707677378

When the tests were run with Python 3.12.0 they worked:

https://github.com/plone/plone.restapi/actions/runs/6999363538/job/19038558131#step:3:13

This appears to be related to: https://github.com/zopefoundation/Zope/issues/1188

I suggest forcing the tests to run with Python 3.12.0, as long as the problem is not fixed.

**Comment by wesleybl** [comment]
@Akshat2Jain can you please create a PR for this?

**Comment by Akshat2Jain** [comment]
sorry @wesleybl for the late response, I have exams going on at my school! :(

**Comment by icemac** [comment]
I do not think this has to do with https://github.com/zopefoundation/Zope/issues/1188. (There we see another traceback.)
This is probably another problem with Python 3.12.1.

**Comment by wesleybl** [comment]
@icemac you are right. I pinned [zope.testrunner = 6.2.1](https://github.com/plone/plone.restapi/commit/b6a31aa0792496519f2914ab7a915beb486b0ced) and the [same error occurred](https://github.com/plone/plone.restapi/actions/runs/7300511080/job/19895292605). Maybe something needs to be changed in plone.app.testing.

@mauritsvanrees FYI.

**Comment by davisagli** [comment]
@wesleybl It looks like this could happen if there was actually an error while setting up the test, so that `"portal"` never got set as an item on the layer.

Probably that testTearDown method should be a bit more careful. But, will that reveal the original error, or is it swallowed? I'm not sure.

**Comment by davisagli** [comment]
I did some debugging; this is related to https://github.com/python/cpython/issues/113267

**Comment by davisagli** [comment]
Reopening since we worked around the issue rather than solving it

**Comment by wesleybl** [comment]
@davisagli while python/cpython#113267 is not fixed, we can make a test [here](https://github.com/plone/plone.app.testing/blob/3dc8a72d846e55db6af72be63f77db0cd5131a37/src/plone/app/testing/layers.py#L291-L292) to make sure the `portal` exists?

**Comment by davisagli** [comment]
@wesleybl I started to do that, but then found that other similar fixes were needed for other layer resources.

**Comment by davisagli** [comment]
@wesleybl The change in Python was [reverted](https://github.com/python/cpython/pull/114994) a few days ago, so I guess it'll be in the next patch release of Python 3.12
