### ISSUE TITLE
Make tests run on plone 5.2

### ISSUE THREAD

**Issue by sunew** [plone/plone.restapi#552]
- [x] Documentation tests / freeze time fails on 5.2
- [x] Failure in test_roles
- [x] test_update_user_password:
MemberData' object has no attribute 'userSetPassword'

- [x] Port allocation plugin on Jenkins leads to different ports
- [ ] test_tus_head_on_not_existing_resource_returns_404
- [ ] we are down to 8 skipped tests

Running under coredev / plip-2177-plone-restapi.cfg

**Comment by tisto** [comment]
https://jenkins.plone.org/view/PLIPs/job/plip-plone-restapi/9/#showFailuresLink

I see two main issues:

1) Port allocation plugin on Jenkins leads to different ports and lots of tests have port 55001 hard coded.

2) test_tus_head_on_not_existing_resource_returns_404

**Comment by sunew** [comment]
@tisto fixed 1.
2.: The TUS problem only happens on Jenkins, not in a local coredev 5.2 build. I looked a bit at it, but have no explanation. It could be related to missing cleanup, and a different test order on Jenkins.

**Comment by tisto** [comment]
@sunew awesome!!! I get one test failure locally on the PLIP job:

```
Failure in test test_tus_head_on_not_existing_resource_returns_404 (plone.restapi.tests.test_tus.TestTUS)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/timo/workspace/buildout.coredev-5.2/src/plone.restapi/src/plone/restapi/tests/test_tus.py", line 155, in test_tus_head_on_not_existing_resource_returns_404
    self.assertEqual(404, response.status_code)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 404 != 200
```

It seems TUS returns a 200 instead of a 404 on non-existing resources. Maybe @lukasgraf or @buchi could have a quick look.

**Comment by tisto** [comment]
Seems to be a test isolation issue. No test failure when I run the test individually:

`bin/test -t test_tus_head_on_not_existing_resource_returns_404`

**Comment by tisto** [comment]
Ok folks, we have a single test to fix before we have a green build:

https://jenkins.plone.org/view/PLIPs/job/plip-plone-restapi/12/testReport/ (TUS)

**Comment by tisto** [comment]
We have another small problem. When running the plone.restapi tests on a release the test_documentation tests do not find the req/resp files because the relative paths don't match:

```
Error in test test_translate_messages_types (plone.restapi.tests.test_documentation.TestDocumentationMessageTranslations)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/timo/workspace/buildout.coredev-5.2/eggs/plone.restapi-3.1.0-py2.7.egg/plone/restapi/tests/test_documentation.py", line 1313, in test_translate_messages_types
    'translated_messages_types', response)
  File "/Users/timo/workspace/buildout.coredev-5.2/eggs/plone.restapi-3.1.0-py2.7.egg/plone/restapi/tests/test_documentation.py", line 106, in save_request_and_response_for_docs
    with open('{}/{}'.format(base_path, '%s.req' % name), 'w') as req:
IOError: [Errno 2] No such file or directory: '/Users/timo/workspace/buildout.coredev-5.2/eggs/plone.restapi-3.1.0-py2.7.egg/plone/restapi/tests/../../../../docs/source/_json/translated_messages_types.req'
```

**Comment by lukasgraf** [comment]
@tisto that should be easy to fix: We should just use the [`pkg_resources` API](https://setuptools.readthedocs.io/en/latest/pkg_resources.html) instead of [building file paths ourselves](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/tests/test_documentation.py#L74-L81). (Assuming the `.req/.resp` files get released with the egg according to the `MANIFEST`).

I can take a look at that.

**Comment by tisto** [comment]
@lukasgraf yep. Thought so as well. Would be great if you could have a look!

**Comment by lukasgraf** [comment]
Turns out just using `pkg_resources` is not enough. Because the `docs` folder is outside a Python package, we also need to make sure it gets included in the installed egg (not just the tar.gz source dist) by specifing the contents we want in `data_files`. And `data_files` doesn't support globs, so we need to enumerate the http example files dynamically in `setup.py`.

Looking into it...

**Comment by tisto** [comment]
We can include those files via the MANIFEST.in, I can take care of that...

**Comment by lukasgraf** [comment]
@tisto they already are - that's not the issue here. They are in fact included in the source distribution (that's what MANIFEST controls). But they are not copied into the *installed egg* (because they are not considered package data, since they are not part of any of the found/listed packages. Or any python package for that matter).

**Comment by sunew** [comment]
@tisto It's funny because I never got the tus failure locally (using coredev), I only see it on Jenkins. Not when running all tests and not when running one test in isolation.

**Comment by sunew** [comment]
"It seems TUS returns a 200 instead of a 404 on non-existing resources. Maybe @lukasgraf or @buchi could have a quick look." Only for the middle one, line 155, '/myuid' - I assume this has been created and not cleaned up by another test. But locally I cannot reproduce.
I just suggest chaning 'myuid' to 'foo' for this single test. Hard to find the cleanup problem when its not hapenning in my build.

**Comment by lukasgraf** [comment]
@tisto see #568 for the fix for running `test_documentation` tests on a released egg.

**Comment by sunew** [comment]
@tisto actually it is reproducable for locally, like this:

`./bin/test -N2 -vvvv -s plone.restapi -t test_tus`

Running the tests twice exposes cleanup problems, and we have a few of them:

```
Failure in test test_length_returns_zero_if_not_set (plone.restapi.tests.test_tus.TestTUSUpload)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/work/playground/plone/plone52devel/src/plone.restapi/src/plone/restapi/tests/test_tus.py", line 481, in test_length_returns_zero_if_not_set
    self.assertEqual(0, tus.length())
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1024



Failure in test test_metadata_returns_empty_dict_if_no_metadata_has_been_set (plone.restapi.tests.test_tus.TestTUSUpload)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/work/playground/plone/plone52devel/src/plone.restapi/src/plone/restapi/tests/test_tus.py", line 513, in test_metadata_returns_empty_dict_if_no_metadata_has_been_set
    self.assertEqual({}, tus.metadata())
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 835, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: {} != {u'length': 1024, u'filename': u'test.pdf'}
- {}
+ {u'filename': u'test.pdf', u'length': 1024}

Failure in test test_offset_returns_size_of_current_file (plone.restapi.tests.test_tus.TestTUSUpload)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/work/playground/plone/plone52devel/src/plone.restapi/src/plone/restapi/tests/test_tus.py", line 490, in test_offset_returns_size_of_current_file
    self.assertEqual(10, tus.offset())
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 10 != 20



Failure in test test_offset_returns_zero_if_file_doesnt_exist (plone.restapi.tests.test_tus.TestTUSUpload)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/work/playground/plone/plone52devel/src/plone.restapi/src/plone/restapi/tests/test_tus.py", line 485, in test_offset_returns_zero_if_file_doesnt_exist
    self.assertEqual(0, tus.offset())
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 20



Failure in test test_tus_head_on_not_existing_resource_returns_404 (plone.restapi.tests.test_tus.TestTUS)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/work/playground/plone/plone52devel/src/plone.restapi/src/plone/restapi/tests/test_tus.py", line 151, in test_tus_head_on_not_existing_resource_returns_404
    response = self.api_session.head(
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 404 != 200




```

**Comment by tisto** [comment]
@lukasgraf ok, got that wrong then. :)

**Comment by petschki** [comment]
@sunew @tisto last night https://jenkins.plone.org/job/pull-request-5.2/912 got 1 failure mentioning wrong ports in plone.restapi tests. So I've came across this issue. What's going wrong there?

**Comment by sunew** [comment]
@petschki Yes, I noticed that too - this was due to a hardcoded 'http://localhost:55001' request, introduced in a PR. I fixed it last night.
