### ISSUE TITLE
Unspecified Archetypes dependency

### ISSUE THREAD

**Issue by tomgross** [plone/plone.restapi#570]
There is an unspecified Archetypes dependency in plone.restapi 3.1.0:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/content/add.py#L12

Please allow to run Plone 5.2 AT free.

Steps to reproduce:

1. Create a buildout with just depending on `Products.CMFPlone` and `plone.restapi` (not the `Plone` egg).
2. Start Plone

```
Running fhnw.education.testing.FhnwEducationLayer:FunctionalTesting tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.460 seconds.
  Set up plone.app.testing.layers.PloneFixtureCould not install product Products.CMFPlacefulWorkflow
 in 16.766 seconds.
  Set up plone.app.event.testing.PAEventLayer in 0.975 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes in 0.884 seconds.
  Set up fhnw.education.testing.FhnwEducationLayer Traceback (most recent call last):
  File "/home/gitlab-runner/Eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 366, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/home/gitlab-runner/Eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 628, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/gitlab-runner/Eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 633, in setup_layer
    layer.setUp()
  File "/home/gitlab-runner/Eggs/plone.app.testing-5.0.8-py2.7.egg/plone/app/testing/helpers.py", line 371, in setUp
    self.setUpZope(portal.getPhysicalRoot(), configurationContext)
  File "/home/gitlab-runner/builds/6d638110/0/webteam/fhnw.education/src/fhnw/education/testing.py", line 26, in setUpZope
    self.loadZCML(package=fhnw.contentwidgets)
  File "/home/gitlab-runner/Eggs/plone.app.testing-5.0.8-py2.7.egg/plone/app/testing/helpers.py", line 432, in loadZCML
    return xmlconfig.file(name, **kw)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/opt/Python2713/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/gitlab-runner/Eggs/z3c.autoinclude-0.3.7-py2.7.egg/z3c/autoinclude/zcml.py", line 54, in includeDependenciesDirective
    includeZCMLGroup(_context, info, 'configure.zcml')
  File "/home/gitlab-runner/Eggs/z3c.autoinclude-0.3.7-py2.7.egg/z3c/autoinclude/zcml.py", line 30, in includeZCMLGroup
    include(_context, filename, includable_package)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/opt/Python2713/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/opt/Python2713/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/opt/Python2713/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/opt/Python2713/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 705, in finish
    args = toargs(context, *self.argdata)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 1397, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py", line 137, in fromUnicode
    value = self.context.resolve(name)
  File "/home/gitlab-runner/Eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 179, in resolve
    mod = __import__(mname, *_import_chickens)
  File "/home/gitlab-runner/Eggs/plone.restapi-3.1.0-py2.7.egg/plone/restapi/services/content/add.py", line 12, in <module>
    from Products.Archetypes.interfaces import IBaseObject
ZopeXMLConfigurationError: File "/home/gitlab-runner/Eggs/fhnw.contentwidgets-1.11.2-py2.7.egg/fhnw/contentwidgets/configure.zcml", line 10.2-10.37
    ZopeXMLConfigurationError: File "/home/gitlab-runner/Eggs/plone.restapi-3.1.0-py2.7.egg/plone/restapi/configure.zcml", line 58.2-58.33
    ZopeXMLConfigurationError: File "/home/gitlab-runner/Eggs/plone.restapi-3.1.0-py2.7.egg/plone/restapi/services/configure.zcml", line 11.2-11.31
    ZopeXMLConfigurationError: File "/home/gitlab-runner/Eggs/plone.restapi-3.1.0-py2.7.egg/plone/restapi/services/content/configure.zcml", line 34.2-39.6
    ImportError: No module named Archetypes.interfaces
```

**Comment by tomgross** [comment]
Can't you switch to `Products.CMFPlone` instead of `Plone` here in the testing buildout: https://github.com/plone/plone.restapi/blob/master/base.cfg#L32

**Comment by tomgross** [comment]
There is another one: https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/atfields.py#L9

**Comment by sunew** [comment]
@tomgross work is already being done here: https://github.com/plone/plone.restapi/pull/542
