### ISSUE TITLE
AttributeError("'NoneType' object has no attribute 'url'",) 

### ISSUE THREAD

**Issue by agitator** [plone/plone.restapi#643]
We're using plone.restapi to index content with ElasticSearch with collective.es.index

Clear and rebuild of catalog fails with 
```
AttributeError("'NoneType' object has no attribute 'url'",) (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: 'NoneType' object has no attribute 'url')
```

```
2018-11-29 15:49:12 INFO elasticsearch PUT http://127.0.0.1:9200/plone_Plone/content/ae0678be09634b75bfdcb75677733ac8?pipeline=attachment_ingest_plone_Plone [status:200 request:0.002s]
2018-11-29 15:49:12 WARNING plone.namedfile.utils PIL can not recognize the image. Image is probably broken or of a non-supported format.
2018-11-29 15:49:12 ERROR plone.namedfile.scaling Could not scale "<plone.namedfile.file.NamedBlobImage object at 0x115e7b848>" of <bound method File.absolute_url of <File at /Plone/myfile.pdf>>
Traceback (most recent call last):
  File "/Users/peter/workspace/plone-es/eggs/plone.namedfile-4.2.5-py2.7.egg/plone/namedfile/scaling.py", line 253, in __call__
    **parameters
  File "/Users/peter/workspace/plone-es/eggs/plone.app.imagecropping-2.1.0-py2.7.egg/plone/app/imagecropping/dx.py", line 48, in create_scale
    **parameters
  File "/Users/peter/workspace/plone-es/eggs/plone.namedfile-4.2.5-py2.7.egg/plone/namedfile/scaling.py", line 200, in create_scale
    **parameters
  File "/Users/peter/workspace/plone-es/eggs/plone.scale-3.0.2-py2.7.egg/plone/scale/scale.py", line 55, in scaleImage
    image = PIL.Image.open(image)
  File "/Users/peter/workspace/plone-es/eggs/Pillow-5.2.0-py2.7-macosx-10.13-x86_64.egg/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
IOError: cannot identify image file <open file u'/Users/peter/workspace/plone-es/var/blobstorage/0x00/0x00/0x00/0x00/0x00/0x0a/0xff/0x7d/0x03bb564b998a8333.blob', mode 'rb' at 0x1155f2a60>
[19] > /Users/peter/workspace/plone-es/srcaddons/plone.restapi/src/plone/restapi/imaging.py(59)get_original_image_url()
```

The object that causes the error is a file with lead image behavior
```
(Pdb++) context
<File at Plone/myfile.pdf>
(Pdb++) context.portal_type
'File'
```

Not sure why it's trying to get `get_original_image_url` in this case...

How should this be fixed?
Checking if there is an actual `images_view` before trying to return scale?
Or just try/except and log the error?

**Comment by jensens** [comment]
We're (ab)suing the serializers directly. But this should IMO work.

**Comment by agitator** [comment]
Found out now, the reason why it fails it because the image is defective...

As far as I see, `get_original_image_url`is used to create the download_url.
So if it's not possible to create such a URL because the image is broken,
I'd put a try/except in there and log the error. Also for the file content type.

**Comment by tisto** [comment]
@agitator are you uploading a PDF as a lead image via plone.restapi? :)

I can confirm that if you create an image with corrupted data via plone.restapi you will get the

`AttributeError("'NoneType' object has no attribute 'url'",)`

error as a response. We might want to improve the error handling here for a better dev experience.

**Comment by agitator** [comment]
should be fixed with https://github.com/plone/plone.restapi/pull/763
