### ISSUE TITLE
Startup fails when Archetypes is there but plone.app.blob not

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.restapi#690]
I am testing out upgrading a client site to Plone 5.2rc1, Python 2.7.  Somehow I end up with a `bin/instance` script that contains `plone.restapi` and `Products.Archetypes` but no `plone.app.blob`. This then cannot startup.
To reproduce, use this buildout:
```
[buildout]
extends =
    http://dist.plone.org/release/5.2rc1-pending/versions.cfg
parts =
    instance
[versions]
plone.restapi = 3.7.1
[instance]
recipe = plone.recipe.zope2instance
user = admin:admin
eggs =
    Products.CMFPlone
    plone.restapi
    Products.Archetypes
```
Traceback on `bin/instance fg` is:
```
Traceback (most recent call last):
  File "/Users/maurits/tmp/testplone/parts/instance/bin/interpreter", line 271, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/Users/maurits/shared-eggs/cp27m/Zope-4.0b8-py2.7.egg/Zope2/Startup/serve.py", line 219, in <module>
    sys.exit(main() or 0)
...
  File "/Users/maurits/shared-eggs/cp27m/plone.restapi-3.7.1-py2.7.egg/plone/restapi/serializer/atfields.py", line 11, in <module>
    from plone.app.blob.interfaces import IBlobField
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/Users/maurits/shared-eggs/cp27m/plone.restapi-3.7.1-py2.7.egg/plone/restapi/serializer/configure.zcml", line 25.8-25.59
    File "/Users/maurits/tmp/testplone/parts/instance/etc/site.zcml", line 16.2-16.23
    File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.2rc1-py2.7.egg/Products/CMFPlone/configure.zcml", line 110.2-114.8
    File "/Users/maurits/shared-eggs/cp27m/plone.restapi-3.7.1-py2.7.egg/plone/restapi/configure.zcml", line 69.2-69.35
    ImportError: No module named blob.interfaces
```
Problem is that `serializer/configure.zcml` conditionally loads some zcml when `Products.Archetypes` is there, but this part of the code then assumes that `plone.app.blob` is available.

I should check why Archetypes is getting included in the client buildout, because I don't want that. (I see I include `plone.app.contenttypes[atrefs]` which does this.)
But maybe `plone.restapi` can be hardened against this case.

**Comment by mauritsvanrees** [comment]
Some notes:

`plone.app.blob` is required by:

```
Products.ATContentTypes
plone.subrequest[archetypes]
plone.restapi[test:python_version < "3"]
plone.app.portlets[test]
Products.CMFPlone 4.3.x
Products.CMFEditions[test]
```

So basically it is only a real dependency of ATContentTypes.
(It looks like Archetypes may fail in [one method](https://github.com/plone/Products.Archetypes/blob/1.16.1/Products/Archetypes/Field.py#L439) without plone.app.blob, but that is not the issue here.)

So it indeed seems best to conditionally load the plone.app.blob serialisers.
I will try that.

**Comment by mauritsvanrees** [comment]
When I fix the first plone.app.blob failure, I run into a similar failure for plone.app.collection:

```
  File "/Users/maurits/community/plone-coredev/5.2/src/plone.restapi/src/plone/restapi/serializer/atfields.py", line 25, in <module>
    from plone.app.collection.field import IQueryField
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/Users/maurits/community/plone-coredev/5.2/src/plone.restapi/src/plone/restapi/serializer/configure.zcml", line 27.8-27.59
    File "/Users/maurits/community/plone-coredev/5.2/src/plone.restapi/parts/instance/etc/site.zcml", line 16.2-16.23
    File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.2.0-py2.7.egg/Products/CMFPlone/configure.zcml", line 110.2-114.8
    File "/Users/maurits/community/plone-coredev/5.2/src/plone.restapi/src/plone/restapi/configure.zcml", line 74.2-74.35
    ImportError: No module named collection.field
```

I will do a similar fix there.

**Comment by mauritsvanrees** [comment]
I have fixed it. To test manually, you should change `base.cfg`:

```
$ git diff
diff --git a/base.cfg b/base.cfg
index c89b0a13..062a5ede 100644
--- a/base.cfg
+++ b/base.cfg
@@ -43,7 +43,8 @@ eggs =
     Plone
     Pillow
     plone.app.debugtoolbar
-    plone.restapi [test]
+    plone.restapi
+    Products.Archetypes
 environment-vars =
     zope_i18n_compile_mo_files true
 
@@ -63,6 +64,8 @@ zcml-additional =
 [test]
 recipe = zc.recipe.testrunner
 eggs = ${instance:eggs}
+    plone.restapi [test]
```
